# Generated by Django 3.0.3 on 2020-03-06 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
