# Generated by Django 3.0.3 on 2020-03-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20200306_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
