# Generated by Django 3.0.3 on 2020-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Policy'), ('A', 'Academic'), ('F', 'Food'), ('E', 'Event')], max_length=20, null=True),
        ),
    ]
