# Generated by Django 3.0.3 on 2020-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_auto_20200306_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Policy', 'Policy'), ('Academic', 'Academic'), ('Food', 'Food'), ('Event', 'Event'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
