# Generated by Django 3.0.3 on 2020-03-08 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_auto_20200307_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorFirst',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='authorLast',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateField(default=datetime.date(2020, 4, 8)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateField(default=datetime.date(2020, 3, 8)),
        ),
    ]
