# Generated by Django 3.0.3 on 2020-03-09 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_auto_20200308_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporter',
            old_name='first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='supporter',
            old_name='last',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateField(default=datetime.date(2020, 4, 9)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateField(default=datetime.date(2020, 3, 9)),
        ),
    ]
