# Generated by Django 3.0.3 on 2020-03-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_auto_20200309_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
