# Generated by Django 3.0.3 on 2020-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_auto_20200309_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=3500),
        ),
    ]
