# Generated by Django 3.0.3 on 2020-09-03 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_auto_20200309_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateField(default=datetime.date(2020, 10, 3)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateField(default=datetime.date(2020, 9, 3)),
        ),
    ]
