# Generated by Django 3.0.3 on 2020-09-04 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_auto_20200903_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateField(default=datetime.date(2020, 10, 4)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateField(default=datetime.date(2020, 9, 4)),
        ),
    ]
