# Generated by Django 3.0.3 on 2020-09-04 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0014_auto_20200904_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='post',
            name='end',
            field=models.DateField(default=datetime.date(2020, 10, 5)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start',
            field=models.DateField(default=datetime.date(2020, 9, 5)),
        ),
    ]
