# Generated by Django 3.0.3 on 2020-09-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0015_auto_20200905_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stuco',
            field=models.CharField(default='', max_length=50),
        ),
    ]
