# Generated by Django 3.0.3 on 2020-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0016_post_stuco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stuco',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
