# Generated by Django 3.0.3 on 2020-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0017_auto_20200905_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stuco',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
